
name: main

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  get-all-needed-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install gdown

      #- name: Download Visual Studio Code Windows
      #  run: wget -O hardwario-code-windows.zip --no-check-certificate https://az764295.vo.msecnd.net/stable/30d9c6cd9483b2cc586687151bcbcd635f373630/VSCode-win32-x64-1.68.1.zip
      - name: Download Visual Studio Code and data folder (Windows)
        run: |
          gdown 1wnhEV1-WMqTPLR6bdHLiGjNptOEANV31
          gdown 1gxQbt5tgI77L6ugHXLpj6xZ76VyQ-X1n

      - name: Create hardwario-code folder
        run: |
          mkdir artifact-windows
          mkdir artifact-windows/hardwario-code
          unzip hardwario-code-windows.zip -d artifact-windows/hardwario-code
          unzip data.zip -d artifact-windows/hardwario-code/

      - uses: actions/upload-artifact@v2
        with:
          name: hardwario-code-windows
          path: ./artifact-windows
  
  windows-export:
    name: Export HARDWARIO Code Windows
    runs-on: windows-latest
    needs: [get-all-needed-files]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v2
        with:
          name: hardwario-code-windows
      - run: ls .
      - run: ls hardwario-code/

      - name: Install all extensions
        run: |
          code.cmd --install-extension cschlosser.doxdocgen
          code.cmd --install-extension jeff-hykin.better-cpp-syntax
          code.cmd --install-extension marus25.cortex-debug
          code.cmd --install-extension ms-vscode.cmake-tools
          code.cmd --install-extension ms-vscode.cpptools
          code.cmd --install-extension ms-vscode.cpptools-extension-pack
          code.cmd --install-extension ms-vscode.cpptools-themes
          code.cmd --install-extension ms-vscode.vscode-serial-monitor
          code.cmd --install-extension ms-vscode-remote.remote-containers
          code.cmd --install-extension ms-vscode-remote.remote-ssh
          code.cmd --install-extension ms-vscode-remote.remote-ssh-edit
          code.cmd --install-extension ms-vscode-remote.remote-wsl
          code.cmd --install-extension twxs.cmake
        working-directory: ./hardwario-code/bin/


