
name: main

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  windows-export:
    name: Export HARDWARIO Code Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install gdown

      - name: Download Visual Studio Code and data folder
        run: |
          gdown 1wnhEV1-WMqTPLR6bdHLiGjNptOEANV31
          gdown 1gxQbt5tgI77L6ugHXLpj6xZ76VyQ-X1n
      
      - name: Unzip all downloaded files
        run: | 
          mkdir hardwario-code
          7z e hardwario-code-windows.zip -ohardwario-code/ -r 
          7z e data.zip -ohardwario-code/ -r

      - run: ls .
      - run: ls hardwario-code/


      #- name: Install all extensions
      #  run: |
      #    code.cmd --install-extension cschlosser.doxdocgen
      #    code.cmd --install-extension jeff-hykin.better-cpp-syntax
      #    code.cmd --install-extension marus25.cortex-debug
      #    code.cmd --install-extension ms-vscode.cmake-tools
      #    code.cmd --install-extension ms-vscode.cpptools
      #    code.cmd --install-extension ms-vscode.cpptools-extension-pack
      #    code.cmd --install-extension ms-vscode.cpptools-themes
      #    code.cmd --install-extension ms-vscode.vscode-serial-monitor
      #    code.cmd --install-extension ms-vscode-remote.remote-containers
      #    code.cmd --install-extension ms-vscode-remote.remote-ssh
      #    code.cmd --install-extension ms-vscode-remote.remote-ssh-edit
      #    code.cmd --install-extension ms-vscode-remote.remote-wsl
      #    code.cmd --install-extension twxs.cmake
      #  working-directory: ./hardwario-code/bin/


