
name: main

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  windows-export:
    name: Export HARDWARIO Code Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install gdown

      - name: Download Visual Studio Code and data folder
        run: |
          gdown 1wnhEV1-WMqTPLR6bdHLiGjNptOEANV31
          gdown 1gxQbt5tgI77L6ugHXLpj6xZ76VyQ-X1n
      
      - name: Unzip all downloaded files
        run: | 
          mkdir hardwario-code
          7z x hardwario-code-windows.zip -r 
          7z x data.zip -ohardwario-code/ -r

      - run: ls .
      - run: ls hardwario-code/
      - run: ls hardwario-code/bin/


      - name: Install all extensions
        shell: cmd
        run: |
          call hardwario-code/bin/code.cmd --install-extension cschlosser.doxdocgen
          call hardwario-code/bin/code.cmd --install-extension jeff-hykin.better-cpp-syntax
          call hardwario-code/bin/code.cmd --install-extension marus25.cortex-debug
          call hardwario-code/bin/code.cmd --install-extension ms-vscode.cmake-tools
          call hardwario-code/bin/code.cmd --install-extension ms-vscode.cpptools
          call hardwario-code/bin/code.cmd --install-extension ms-vscode.cpptools-extension-pack
          call hardwario-code/bin/code.cmd --install-extension ms-vscode.cpptools-themes
          call hardwario-code/bin/code.cmd --install-extension ms-vscode.vscode-serial-monitor
          call hardwario-code/bin/code.cmd --install-extension ms-vscode-remote.remote-containers
          call hardwario-code/bin/code.cmd --install-extension ms-vscode-remote.remote-ssh
          call hardwario-code/bin/code.cmd --install-extension ms-vscode-remote.remote-ssh-edit
          call hardwario-code/bin/code.cmd --install-extension ms-vscode-remote.remote-wsl
          call hardwario-code/bin/code.cmd --install-extension twxs.cmake

