
name: main

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  get-all-needed-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download Visual Studio Code Windows
        run: wget -O hardwario-code-windows.zip --no-check-certificate https://az764295.vo.msecnd.net/stable/30d9c6cd9483b2cc586687151bcbcd635f373630/VSCode-win32-x64-1.68.1.zip

      - name: Create hardwario-code folder
        run: |
          mkdir hardwario-code
          unzip hardwario-code-windows.zip -d hardwario-code

      - uses: actions/upload-artifact@v2
        with:
          name: hardwario-code-windows
          path: ./hardwario-code
  
  windows-export:
    name: Export HARDWARIO Code Windows
    runs-on: windows-latest
    needs: [get-all-needed-files]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v2
        with:
          name: hardwario-code-windows
      - run: ls .
      - run: ls hardwario-code/
