
name: main

on:
  release:
    types: [published]

jobs:
  windows-export:
    name: Export HARDWARIO Code Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install gdown

      - name: Get latest HARDWARIO Tower VSCode Extension 
        uses: robinraju/release-downloader@v1.4
        with:
          repository: "hardwario/hardwario-tower-vscode-extension"
          latest: true
          fileName: "*.vsix"
        
      - run: mv *.vsix hardwario-tower.vsix
        
      - name: Download Visual Studio Code and data folder
        run: |
          gdown 1wnhEV1-WMqTPLR6bdHLiGjNptOEANV31
          gdown 1gxQbt5tgI77L6ugHXLpj6xZ76VyQ-X1n
      
      - name: Unzip all downloaded files
        run: | 
          mkdir hardwario-code
          7z x hardwario-code-windows.zip -r 
          7z x data.zip -ohardwario-code/ -r

      - name: Install all extensions
        shell: cmd
        run: |
          call hardwario-code/bin/code.cmd --install-extension cschlosser.doxdocgen
          call hardwario-code/bin/code.cmd --install-extension jeff-hykin.better-cpp-syntax
          call hardwario-code/bin/code.cmd --install-extension marus25.cortex-debug
          call hardwario-code/bin/code.cmd --install-extension ms-vscode.cmake-tools
          call hardwario-code/bin/code.cmd --install-extension ms-vscode.cpptools
          call hardwario-code/bin/code.cmd --install-extension ms-vscode.cpptools-extension-pack
          call hardwario-code/bin/code.cmd --install-extension ms-vscode.cpptools-themes
          call hardwario-code/bin/code.cmd --install-extension ms-vscode.vscode-serial-monitor
          call hardwario-code/bin/code.cmd --install-extension ms-vscode-remote.remote-containers
          call hardwario-code/bin/code.cmd --install-extension ms-vscode-remote.remote-ssh
          call hardwario-code/bin/code.cmd --install-extension ms-vscode-remote.remote-ssh-edit
          call hardwario-code/bin/code.cmd --install-extension ms-vscode-remote.remote-wsl
          call hardwario-code/bin/code.cmd --install-extension twxs.cmake
          call hardwario-code/bin/code.cmd --install-extension hardwario-tower.vsix

      - name: Zip the final product
        run: 7z a -tzip hardwario-code-windows hardwario-code/*

      - name: Publish the extension;
        uses: softprops/action-gh-release@v0.1.5
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          files: hardwario-code-windows.zip
